### ISSUE TITLE
problems when generating index of genome

### ISSUE THREAD

**Issue by JieWu2012** [erhard-lab/gedi#50] opened 2020-07-28 17:56 UTC
Hi Florian, 
When I generate the index for the curated genome and gtf file with: 
**gedi -e IndexGenome -s test1.fa -f ./ -a test.gtf  -D**
I got such problem: 

2020-07-28 19:39:59.641 INFO OS: Linux 3.10.0-862.11.6.el7.x86_64 amd64
2020-07-28 19:39:59.680 INFO Java: OpenJDK 64-Bit Server VM 1.8.0_121-b15
2020-07-28 19:39:59.761 INFO Discovering classes in classpath
2020-07-28 19:39:59.865 INFO Preparing simple class references
2020-07-28 19:39:59.936 INFO Gedi version 1.0.2 (JAR) startup
2020-07-28 19:39:59.937 INFO Command: gedi -e IndexGenome -s test1.fa -f ./ -a test.gtf -D
2020-07-28 19:39:59.982 SEVERE Could not load startup FxStartup.class in /home/jwu/software/Price_1.0.3b/gedi.jar
An error occurred: Your fasta file appears to be truncated: test1.fa
java.io.IOException: Your fasta file appears to be truncated: test1.fa
	at gedi.util.io.text.fasta.index.FastaIndexFile.create(FastaIndexFile.java:87)
	at gedi.util.io.text.fasta.index.FastaIndexFile.create(FastaIndexFile.java:57)
	at executables.IndexGenome.start(IndexGenome.java:546)
	at executables.IndexGenome.main(IndexGenome.java:81)
2020-07-28 19:40:00.014 INFO Finished: gedi -e IndexGenome -s test1.fa -f ./ -a test.gtf -D
2020-07-28 19:40:00.015 INFO Took 383ms

It seems the genome sequence is problematic and I find that only if I add another meaningless sequence with **two lines** (see attaching file test2.fa), the problem is solved. Could you tell me what is wrong here? 

Even with the new genome sequence test2.fa, I got another problem: 

2020-07-28 19:42:52.776 INFO OS: Linux 3.10.0-862.11.6.el7.x86_64 amd64
2020-07-28 19:42:52.815 INFO Java: OpenJDK 64-Bit Server VM 1.8.0_121-b15
2020-07-28 19:42:52.892 INFO Discovering classes in classpath
2020-07-28 19:42:52.999 INFO Preparing simple class references
2020-07-28 19:42:53.080 INFO Gedi version 1.0.2 (JAR) startup
2020-07-28 19:42:53.081 INFO Command: gedi -e IndexGenome -s test2.fa -f ./ -a test.gtf -D
2020-07-28 19:42:53.128 SEVERE Could not load startup FxStartup.class in /home/jwu/software/Price_1.0.3b/gedi.jar
An error occurred: Fasta file is empty: ./test.transcripts.fasta
java.io.IOException: Fasta file is empty: ./test.transcripts.fasta
	at gedi.util.io.text.fasta.index.FastaIndexFile.create(FastaIndexFile.java:70)
	at gedi.util.io.text.fasta.index.FastaIndexFile.create(FastaIndexFile.java:57)
	at gedi.util.io.text.fasta.FastaFile.obtainAndOpenDefaultIndex(FastaFile.java:69)
	at executables.IndexGenome.start(IndexGenome.java:622)
	at executables.IndexGenome.main(IndexGenome.java:81)
2020-07-28 19:42:53.185 INFO Finished: gedi -e IndexGenome -s test2.fa -f ./ -a test.gtf -D
2020-07-28 19:42:53.186 INFO Took 419ms 
 
which indicates that gtf file can't be recognized, right? But I can't find out what goes wrong in my gtf. It has "transcript", "exon", "CDS" and "start codon" etc. 

Thank you very much for your help!

test1.fa: 
![Screen Shot 2020-07-28 at 19 51 24](https://user-images.githubusercontent.com/4727669/88702640-e67cb780-d10b-11ea-9fc4-c73d128bf84d.png)
test2.fa: 
![Screen Shot 2020-07-28 at 19 51 50](https://user-images.githubusercontent.com/4727669/88702689-f399a680-d10b-11ea-85f0-2da21084c3cd.png)
test.gtf: 
![Screen Shot 2020-07-28 at 19 52 06](https://user-images.githubusercontent.com/4727669/88702717-fac0b480-d10b-11ea-80b4-9b7a89dca979.png)

**Comment by florianerhard** [comment] 2020-07-29 22:29
Which release are you using?

The first error comes from a bug in the automated recognition of truncated fasta files (this happens from time to time when you download them!). This should be fixed in the next release.

Regarding your second error: I cannot reproduce it (I tried to prepare similar files like the ones you show here). Could you please post the contents of these files here instead of screenshots?

**Comment by jasonwufree2012** [comment] 2020-07-30 08:49
Hi Florian, 
Thanks for the quick reply. 
I use gedi "1.8.0_121". And I attached the files below but changed the names since *.fa or *.gtf are not acceptable here. 
[test_gtf.txt](https://github.com/erhard-lab/gedi/files/5000071/test_gtf.txt)
[test1_fa.txt](https://github.com/erhard-lab/gedi/files/5000072/test1_fa.txt)
[test2_fa.txt](https://github.com/erhard-lab/gedi/files/5000075/test2_fa.txt)

**Closed** 2022-01-19 08:01 UTC
