### ISSUE TITLE
Exception in parallel iterator thread!

### ISSUE THREAD

**Issue by vladie0** [erhard-lab/gedi#13] opened 2018-06-12 12:26 UTC
Dear developers, 

attempting to run price I get the following error in several different datasets:
Exception in parallel iterator thread!
(I've tried to execute price with different parameters, threads, ...

full error description:
2018-06-12 11:06:43.814 INFO Command: gedi -e Price -percond -nthreads 1 -reads bamlist.bamlist -genomic homo_sapiens.92 -fdr 0.1 -prefix znrxdpikc
2018-06-12 11:06:44.033 INFO Discovering classes in classpath
2018-06-12 11:06:44.065 INFO Preparing simple class references
2018-06-12 11:06:44.119 INFO Gedi 1.0.2 (JAR) startup
2018-06-12 11:06:44.450 INFO Reading oml /home/vladie/.gedi/genomic/homo_sapiens.92.oml
2018-06-12 11:06:44.465 INFO Done reading oml /home/vladie/.gedi/genomic/homo_sapiens.92.oml
2018-06-12 11:06:47.106 INFO Estimating maxpos...
2018-06-12 11:06:47.135 INFO Clustering reads
2018-06-12 11:08:26.384 INFO Found 251370 clusters without looking at annotation
2018-06-12 11:08:28.401 INFO Found 49042 clusters after looking at annotation
2018-06-12 11:08:29.051 INFO Found 15028 clusters after filtering with read/region count
2018-06-12 11:12:32.097 INFO Using maxpos=13 (0)
2018-06-12 11:12:32.098 INFO Estimate parameters
Correcting from 0 to 12 (desired: 13)
2018-06-12 13:08:52.746 INFO LL=-Infinity
2018-06-12 13:08:55.647 INFO Codon inference
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCodonInference@20d8673
Could not run gedi.riboseq.javapipeline.PriceCodonInference@20d8673
Exception in parallel iterator thread!

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files

Could you investigate this issue ? 
Thank you

**Comment by vladie0** [comment] 2018-06-13 08:16
This is the error obtained if ran with -D:

2018-06-13 10:41:35.298 INFO Command: gedi -e Price -D -percond -nthreads 10 -reads bamlist.bamlist -genomic homo_sapiens.92 -fdr 0.1 -prefix rpnjakwel
2018-06-13 10:41:35.528 INFO Discovering classes in classpath
2018-06-13 10:41:35.556 INFO Preparing simple class references
2018-06-13 10:41:35.593 INFO Gedi 1.0.2 (JAR) startup
2018-06-13 10:41:35.892 INFO Reading oml /home/vladie/.gedi/genomic/homo_sapiens.92.oml
2018-06-13 10:41:35.907 INFO Done reading oml /home/vladie/.gedi/genomic/homo_sapiens.92.oml
2018-06-13 10:41:38.340 INFO Estimating maxpos...
2018-06-13 10:41:38.364 INFO Clustering reads
2018-06-13 10:43:19.098 INFO Found 251370 clusters without looking at annotation
2018-06-13 10:43:21.223 INFO Found 49042 clusters after looking at annotation
2018-06-13 10:43:21.947 INFO Found 15028 clusters after filtering with read/region count
2018-06-13 10:47:36.685 INFO Using maxpos=13 (0)
2018-06-13 10:47:36.687 INFO Estimate parameters
Correcting from 0 to 12 (desired: 13)
2018-06-13 10:59:20.471 INFO LL=-Infinity
2018-06-13 10:59:22.826 INFO Codon inference
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCodonInference@6cb9d137
Could not run gedi.riboseq.javapipeline.PriceCodonInference@6cb9d137
Exception in parallel iterator thread!

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCodonInference@6cb9d137
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:222)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
        at gedi.util.program.GediProgram.run(GediProgram.java:204)
        at executables.Price.main(Price.java:68)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceCodonInference@6cb9d137
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in parallel iterator thread!
        at gedi.util.functions.ParallelizedIterator.fatal(ParallelizedIterator.java:221)
        at gedi.util.functions.ParallelizedIterator.tryNext(ParallelizedIterator.java:189)
        at gedi.util.functions.ParallelizedIterator.hasNext(ParallelizedIterator.java:150)
        at gedi.riboseq.javapipeline.PriceCodonInference.execute(PriceCodonInference.java:106)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        ... 7 more

**Comment by florianerhard** [comment] 2018-06-14 09:57
The line ` 2018-06-12 13:08:52.746 INFO LL=-Infinity` here is what is worrying me. As far as I can tell, this can only happen if the codon model inference does not see any data.  Could you do

```
gedi Nashorn -e 'println(Genomic.get("homo_sapiens.92").getTranscripts().ei().filter(function(r) r.getData().isCoding()).count())'
```

in the shell? How did you map reads?

Best,
Florian

**Comment by vladie0** [comment] 2018-06-25 06:50
Dear Florianehard, 

Did you manage to make any advancements in solving the issue ? Is there anything I can assist you with ? 

Thank in advance, 
Vladie0

**Comment by florianerhard** [comment] 2018-06-27 21:56
Dear Vladie0,
sorry for the long delay, we just submitted an important manuscript. 

As far as I can tell, the bam file does not contain MD tags, and Price needs them to determine terminal mismatches. Could you let STAR include MD tags: `` --outSAMattributes MD``

I hope this helped!

Best,
Florian

**Comment by vladie0** [comment] 2018-07-02 07:03
Dear Florian, 
Unfortunately, this did not solve the issue,
kind regards,
vladie

**Comment by vladie0** [comment] 2018-07-18 09:56
Dear Florianerhard, 
Are there any advancements in the issue. By this time I found +- 6 distinct datasets, publically available, which cause this error. The STAR tag adjustment do not solve the issue.

Kind Regards,
Vladie0

**Comment by florianerhard** [comment] 2018-08-01 08:12
Dear Vladie0,

again, sorry for the long delay. It is very difficult to fix such an error without being able to reproduce it here on my machine. Could you provide a minimal example that produces this error? Does your bam file now include the MD tags? Is there anything else special about those 6 data sets?

Best,
Florian

**Comment by vladie0** [comment] 2018-08-02 08:27
Dear Florianhard, 
All files (30+ distinct RIBO-seq datasets), from different sources, were processed in the same manner. Most of them are successfully processed with PRICE, while 6 of them throw the exception described above. It's unlikely that the issue would reside in the STAR processing as all files are processed in the same manner, moreover, explicitly including the MD tags does NOT resolve the issue. I already provided the STAR output of a RIBO-seq dataset that should allow you to reproduce the error.

The following link contains the full STAR output folder of another project where STAR fails to process the dataset correctly, using this bam file with ENS v92 should reproduce the error as I tried this on 2 distinct machines. (only a snippet of the SAM file was uploaded due to file size)

dropbox link to STAR files:
https://www.dropbox.com/s/hxbstb5dux8bvzo/fastq1.tar.gz?dl=0

link to RAW data files:
ftp://ftp.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByStudy/sra/SRP/SRP056/SRP056098/
mapping statistics supplied dataset:
sample                    type        total       mapped_U    mapped_M    mapped_T    unmapped    map_freq_U  map_freq_M  map_freq_T       
------------------------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------  -----------------
su_2015_STAR_N_92.fastq1  rRNA        175879180                           103090297   72788883                            0.586142697504048
su_2015_STAR_N_92.fastq1  genomic     66625093    53503248    10809057    64312305    2312788     0.80304950  0.16223702  0.965286532508105
su_2015_STAR_N_92.fastq1  tRNA        69987292                            3362199     66625093                            0.048040135629193
su_2015_STAR_N_92.fastq1  snRNA       72788883                            2801591     69987292                            0.038489270401360
su_2015_STAR_N_92.fastq1  phix        177472911                           1593731     175879180                           0.008980136692523

Alternatively, these datasets will be reported as unable to be processed with PRICE with a reference to this issue thread.

Kind Regards,
Vladie0

**Comment by florianerhard** [comment] 2018-08-02 09:47
Dear Vladie0,

BAM files supplied to PRICE must comply to two conditions: No softclips, and MD attribute available (which is stated in the FAQ on the wiki page). 

Otherwise (whether it may or may not run through) you will get suboptimal results (and depending on the data set, they can be really bad). The reason for that is that PRICE needs to know whether the first read base does or does not map to the reference, which is indicative of an untemplated nucleotide addition (can happen >20% of the reads). Untemplated additions are crucial in defining the P site. Without this information, many reads will be off by 1nt, and this interferes with the estimation of the codon model.

The BAM files you supplied both had no MD attribute, leading to this error (the next release will print a more meaningful error message for that). 

I really wonder how PRICE could run through for all the other cases. It would be great if you could provide a BAM file where it did run through.

You said writing the MD attribute into the BAM file dit not solve the issue? Did you get the same error? Could you supply a BAM file with MD attribute for me to reproduce this error?

Best,
Florian

**Comment by ataylor22** [comment] 2019-05-14 18:08
Dear Dr. Erhard,
While attempting to run PRICE I received the following error:

~/path$ gedi -e Price -reads path.cit -genomic Homo_sapiens_HG19_GRCh37_82 -prefix price/test1 -D -progress -novelTranscripts 

2019-04-18 19:02:38.767 INFO Command: gedi -e Price -reads path.cit -genomic Homo_sapiens_HG19_GRCh37_82 -prefix price/test1 -D -progress -novelTranscripts
2019-04-18 19:02:39.253 INFO Discovering classes in classpath
2019-04-18 19:02:39.429 INFO Preparing simple class references
2019-04-18 19:02:39.558 INFO Gedi 1.0.2 (JAR) startup
2019-04-18 19:02:39.899 INFO Reading oml /home/hamiltonat/.gedi/genomic/Homo_sapiens_HG19_GRCh37_82.oml
2019-04-18 19:02:39.909 INFO Done reading oml /home/hamiltonat/.gedi/genomic/Homo_sapiens_HG19_GRCh37_82.oml
2019-04-18 19:02:41.262 INFO Estimating maxpos...
2019-04-18 19:02:41.269 INFO Clustering reads
Processed 487035 elements in 6s 672ms (Throughput: 72985.9/sec)
Processed 487035 elements in 9s 114ms (Throughput: 53438.1/sec)
Processed 487035 elements in 9s 630ms (Throughput: 50574.8/sec)
2019-04-18 19:02:50.908 INFO Found 147377 clusters without looking at annotation
Processed 147377 elements in 910ms (Throughput: 161952.7/sec)
2019-04-18 19:02:51.980 INFO Using maxpos=12 (Merged)
2019-04-18 19:02:51.981 INFO Estimate parameters
\ Model inference: Repeat 0, Iteration 9: LL=-3.81288e+06; bestLL=-Infinity 702 (2562.0/sec)2019-04-18 19:02:52.269 INFO Found 37010 clusters after looking at annotation
/ Model inference: Repeat 1, Iteration 16: LL=-3.81333e+06; bestLL=-3.81319e+06 2311 (3320.4/sec)2019-04-18 19:02:52.778 INFO Found 16311 clusters after filtering with read/region count
Processed 6085528 elements in 9s 281ms (Throughput: 655697.4/sec)
2019-04-18 19:03:01.366 INFO LL=-3.81046e+06
2019-04-18 19:03:01.393 INFO Codon inference
Processed 16311 elements in 13s 811ms (Throughput: 1181.0/sec)
2019-04-18 19:03:15.307 INFO Writing codon index
2019-04-18 19:03:15.307 INFO Train start prediction
2019-04-18 19:03:15.307 INFO Calibrate noise model

Processed 15855 elements in 980ms (Throughput: 16178.6/sec)
| Start prediction training 11+:1940953-1959722     40 (33.4/sec)
- Viewer indices 2+:20647812-20647815   17374 (14502.5/sec)2019-04-18 19:03:16.562 INFO Considering 41 ORFs for start trProcessed 41 elements in 1s 302ms (Throughput: 31.5/sec)
| Viewer indices 2+:43958710-43958713   19959 (11678.8/sec)[GediProgram-1-thread-2] INFO smile.math.Math - L-BFGS: initial function value: 170.51
[GediProgram-1-thread-2] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 101.62
[GediProgram-1-thread-2] INFO smile.math.Math - L-BFGS: the function value after  20 iterations: 100.32
[GediProgram-1-thread-2] INFO smile.math.Math - L-BFGS: the function value after  30 iterations: 99.421
[GediProgram-1-thread-2] INFO smile.math.Math - L-BFGS: the function value after  40 iterations: 99.401
[GediProgram-1-thread-2] INFO smile.math.Math - L-BFGS: the function value after  50 iterations: 99.401
[GediProgram-1-thread-2] INFO smile.math.Math - L-BFGS: initial function value: 170.51
[GediProgram-1-thread-2] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 102.23
[GediProgram-1-thread-2] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 102.22
- Viewer indices 1-:180746090-180746093 20183 (11144.7/sec)2019-04-18 19:03:17.160 INFO Infer ORFs
- Viewer indices 2+:174231988-174231991 43337 (7609.7/sec)
| PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceOrfInference@75ba4d0c
Could not run gedi.riboseq.javapipeline.PriceOrfInference@75ba4d0c
Exception in parallel iterator thread!
/ by zero

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files

\ Viewer indices 3+:139227338-139227341 44750 (7708.9/sec)
/ java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceOrfInference@75ba4d0c
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:223)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
        at gedi.util.program.GediProgram.run(GediProgram.java:204)
        at executables.Price.main(Price.java:69)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceOrfInference@75ba4d0c
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Exception in parallel iterator thread!
        at gedi.util.functions.ParallelizedIterator.fatal(ParallelizedIterator.java:229)
        at gedi.util.functions.ParallelizedIterator.tryNext(ParallelizedIterator.java:197)
        at gedi.util.functions.ParallelizedIterator.hasNext(ParallelizedIterator.java:158)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at gedi.riboseq.utils.RiboUtils.lambda$processCodonsSink$4(RiboUtils.java:107)
        at gedi.riboseq.utils.RiboUtils.processCodons(RiboUtils.java:147)
        at gedi.riboseq.utils.RiboUtils.processCodonsSink(RiboUtils.java:107)
        at gedi.riboseq.javapipeline.PriceOrfInference.execute(PriceOrfInference.java:118)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        ... 7 more
Caused by: java.lang.ArithmeticException: / by zero
        at jdistlib.math.spline.SmoothSpline.formKnots(SmoothSpline.java:155)
        at jdistlib.math.spline.SmoothSpline.fit(SmoothSpline.java:1441)
        at jdistlib.math.spline.SmoothSpline.fitDFMatch(SmoothSpline.java:1296)
        at gedi.riboseq.inference.orf.NoiseModel.computeMeanSpline(NoiseModel.java:188)
        at gedi.riboseq.inference.orf.NoiseModel.getProbability(NoiseModel.java:141)
        at gedi.riboseq.inference.orf.NoiseModel.getProbability0(NoiseModel.java:121)
        at gedi.riboseq.inference.orf.OrfInference.inFrameTestCandidate(OrfInference.java:1271)
        at gedi.riboseq.inference.orf.OrfInference.inFrameTest(OrfInference.java:1079)
        at gedi.riboseq.inference.orf.OrfInference.inferOrfs(OrfInference.java:433)
        at gedi.riboseq.javapipeline.PriceOrfInference.lambda$null$1(PriceOrfInference.java:121)
        at gedi.util.FunctorUtils$DemultiplexIterator.lookAhead(FunctorUtils.java:106)
        at gedi.util.FunctorUtils$DemultiplexIterator.hasNext(FunctorUtils.java:90)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:638)
        at gedi.util.FunctorUtils$SideEffectIterator.hasNext(FunctorUtils.java:719)
        at gedi.util.functions.ExtendedIterator.toCollection(ExtendedIterator.java:400)
| Viewer indices 3+:139227338-139227341 44918 (7667.8/sec)

I ran the Nashorn script you suggested and received this output: 

gedi Nashorn -e\'println(Genomic.get("Homo_sapiens_HG19_GRCh37_82").getTranscripts().ei().filter(function(r) r.getData().isCoding()).count())'
2019-05-14 17:48:32.623 INFO Command: gedi Nashorn -e println(Genomic.get("Homo_sapiens_HG19_GRCh37_82").getTranscripts().ei().filter(function(r) r.getData().isCoding()).count())
2019-05-14 17:48:33.031 INFO Discovering classes in classpath
2019-05-14 17:48:33.165 INFO Preparing simple class references
2019-05-14 17:48:33.287 INFO Gedi 1.0.2 (JAR) startup
2019-05-14 17:48:34.077 INFO Reading oml /home/hamiltonat/.gedi/genomic/Homo_sapiens_HG19_GRCh37_82.oml
2019-05-14 17:48:34.097 INFO Done reading oml /home/hamiltonat/.gedi/genomic/Homo_sapiens_HG19_GRCh37_82.oml
94587

Regards, 
Anika

**Closed** 2022-01-19 08:01 UTC
